name: Continuous Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the cloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          APP_BACKEND_URL: ${{ secrets.APP_BACKEND_URL }}
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
          docker build --build-arg APP_BACKEND_URL=${APP_BACKEND_URL} -t asia-southeast1-docker.pkg.dev/myfoodshop-420307/repo-foodshop/frontend:latest .
          docker push asia-southeast1-docker.pkg.dev/myfoodshop-420307/repo-foodshop/frontend:latest
      - name: Deploy to Cloud Run
        env:
          SERVICE_NAME: frontend
          IMAGE_URL: asia-southeast1-docker.pkg.dev/myfoodshop-420307/repo-foodshop/frontend:latest
          REGION: asia-southeast1
          APP_BACKEND_URL: ${{ secrets.APP_BACKEND_URL }}
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_URL \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars APP_BACKEND_URL=$APP_BACKEND_URL
